systemjs/builder

lib/builder.js
Looks like `--skip-source-maps` was broken in https://github.com/systemjs/builder/commit/b4ae08e7ad4770cfef2a4bca006248ce190fd399
=> Fixup null error

README.md, lib/builder.js
This PR is the same as #57 without the rebase mess.
This allows to set minify: true, mangle: false in config. mangle defaults to true to not break bc.
This is needed if you use angular and want to use Implicit Annotation e.g.
Being able to remove whitespace and comments during the build is probably still desirable.
=> expose mangle option, allows for minifying without mangling

.gitignore, index.js, lib/builder.js, test/run-build.js
@guybedford let me know if you're happy with this approach, most notably the API (return file-contents string within promise). 
Perhaps a stream is more suitable, and I'm not sure what was meant by "memory FS". Looked at things like https://github.com/tschaub/mock-fs, but that sort of evil seems doesn't seem to belong outside of testing, and not sure the value it would add in the scenario vs return an inlined-file or a dictionary of the separate files.
Need to hook up Uglify for in-memory usage, and refactor my goop (been a while, JavaScript)
Closes #54
=> Output to memory

README.md
Many code blocks in `README.md` are indented by two extra spaces. This removes them so indentation is correct when copying examples.
=> clean up indentation

lib/builder.js
This should actually make production configuration unnecessary in most cases.
This also adds a `modules` array to the output object allowing for easy population of bundles.
There is also a new static method, `Builder.getDepCache(tree)` for easier depCache generation.
=> Default to normalize

lib/builder.js
I've defaulted it to `true` to match the current behaviour in minify.
Looks like this was missed [when whitelisting the options](https://github.com/systemjs/builder/commit/2eee61e8e778bfacc0789a280eb7489a1c963d3b).
---
[`Builder.prototype.buildTree`](https://github.com/systemjs/builder/blob/ed83dff78c4bdb114fa5dd3abf35fd00133bf0b2/lib/builder.js#L175-L183) will `processOpts` before passing them to [`writeOutputs`](https://github.com/systemjs/builder/blob/9859a29a7a5a99273e280c14043573a8df93c947/lib/output.js#L135), removing the `mangle` option if we pass it in. Then [`minify`](https://github.com/systemjs/builder/blob/9859a29a7a5a99273e280c14043573a8df93c947/lib/output.js#L82) will mangle anyway.
=> Add "mangle" to allowed options

lib/sourcemaps.js, package.json, test/sourcemaps.js
It's a bit messy - old POC code just rebased. 
Worst part is that it can't rely on existing `sourcesContent` due to (I believe) an issue in Traceur's transitive source maps.
=> Pessimistic support for `includeSourcesContent`

lib/builder.js
This fix means that given a loader/pluginLoader pair, whenever pluginLoader.instantiate is called, global.System gets set to loader.
See issue #154.
=> fix(reset): fix for _nodeRequire not being set in plugin (fixes #154)

README.md
Added documentation to warn users that SFX bundles can only use addition and wildcard arithmetic.
=> Update README to describe bundleSFX arithmetic

lib/builder.js, lib/output.js, lib/sourcemaps.js, lib/utils.js
@guybedford 
This cleans up sticky tape around `file:`, which could go horribly wrong (see #157) and for example rebase absolute URLs against a relative baseURL.
Presenting two approaches: strict (see after first commit) and permissive (see after last commit)
If we decide to go with either of these I'll add some tests.
=> URL hygiene

compilers/global.js
specifying more than one global in the meta config breaks the builder.
=> extraneous comma in global expression builder

templates/global-helpers.js
IE < 9 does not define `hasOwnProperty` for host objects (see http://stackoverflow.com/a/8159434). This seems to have been fixed in systemjs core already (see https://github.com/systemjs/systemjs/commit/1ee77a#diff-5010b5e8eb34234db769e98607569c59L6).
I wasn't sure if there was some automatic way of updating the helper from `systemjs/systemjs` so I've only touched the line that's broken. Let me know if there's anything else I need to do.
=> Fix undefined `hasOwnProperty` in IE8

lib/compile.js, lib/trace.js, lib/utils.js, package.json, test/canonicals.js, test/conditional-canonicals.js, test/test-post-order.js
This PR fixes indeterministic source order in bundles, which means that bundle filename hashing will be consistent for unchanged sources.
Further more it order the sources in a way so dependencies for modules always comes before the module that requires it. In cases where parsing the bundle itself causes side effects by one module, which a module later in the load order depends on, bundling does not break these implicit side effect dependencies. This improves robustness for compatibility with non-module loader code.
Tests are not passing yet. I have one or two quirks that I still need to resolve
=> Bundle source order in post order traversal order

lib/builder.js
saveForReset was not beign passed from executeConfigFile to builder.config. This was causing build.config to work improperly.
=> Add missing saveForReset parameter

lib/output.js
When using the SystemJS builder with enabled minify option builds seem 
to be non-deterministic. Compiling one and the same source results in 
different results which makes computing checksums (and using them as a
cache buster) for those files useless.
The problem seems to be caused by UglifyJS's compute_char_frequency 
method which leads to unstable name mangling (at least in some cases). 
Removing that method from the builder has fixed that problem 
immediately.
The official Grunt Uglify task for instance disabled that method for 
the same reason. 
See: https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js#L137
=> Use stable name mangling for deterministic builds

lib/builder.js, test/test-build-cache.js
`builder.invalidate('path')` or `builder.invalidate('some/wildcard/*')`
Invalidation works in full module name space identical to the loader.
Invalidation is synchronous and returns the array of fully-normalized names invalidated - eg `['file:///path/to/project/x.js']`.
Inspired by the work of @jackfranklin in https://github.com/jackfranklin/jspm-dev-builder/blob/master/index.js!
=> Builder invalidation API

README.md, lib/arithmetic.js, lib/builder.js, lib/trace.js, test/test-build.js
This is a first draft on how to hook static string data. This would allow you to build the string source of a file yourself, then pass it into the builder to resolve dependencies. Example:
```javascript
builder.build('foo.js', 'bar.js', {
fetch: function (data) {
if (data.name.indexOf('foo.js') !== -1) { return 'var bar = 2;'; }
}
});
```
Fixes #330
=> Add fetch hook into tracer.

lib/builder.js
Enabled full System Loader support in `executeConfigFile` in `builder.js`. This allows multiple System.config invocations to have full access to the System Loader API. The use case for this commit is to be able to load additional config files which add additional used defined mapped paths that incorporate existing normalized paths from loaded package dependencies.
As requested in #377 this pull request exposes the entire System Loader API to config loading in the Builder API. In particular the functions `loadConfig` & `loadConfigSync` invokes `executeConfigFile`.
Please see #377 for full use case description. This PR supersedes both #377 and #378
=> Enabled full System Loader support in executeConfigFile

lib/builder.js, test/test-load-config.js
This adds the testcase for two builders calling loadConfig in parallel, to support use case like this:
var builder1 = new Builder();
var builder2 = new Builder();
builder1.loadConfig('config1.js').then(function() { ... });
builder2.loadConfig('config2.js').then(function() { ... });
The test fails, and the second commit attempts to fix it.
See also #384 that might be related.
=> Two builders calling loadConfig in parallel

lib/trace.js
In certain cases (plugins) `isLoadFresh` tries to access the `loads` variable, which simply isn't present in the given context.
This PR fixes this issue.
=> fixed isLoadFresh accessed non existant loads variable

lib/trace.js
If the getLoadRecord returned promised rejected (like when transpiler exception from syntax error in the module)
the reference to that (rejected)promise kept cached in self.tracing
and further calls to getLoadRecored for that module returned the promise cached in self.tracing
That's breaks continuous builds (tools like jspm-dev-builder)  
fixes jackfranklin/jspm-dev-builder#15
fixes jackfranklin/jspm-dev-builder#11
fixes #433
=> Fix Trace getLoadRecord error recovery

compilers/register.js
tree.args is an Object and has no method "concat"... tree.args.args is the array we're looking for.
=> bug fix in register.js

lib/builder.js, test/test-load-config.js
another tweak to executeConfigFile
require requires special handling because it's not accessible as global.require - "require isn't actually a global but rather local to each module" as they say at https://nodejs.org/api/globals.html#globals_require
well it will belong to global in the config file execution context because I see no other way around it.
=> fix #436: make require() available to config code 

lib/utils.js
Not sure what the long-term plan is, but traceur main branch is at 0.96 already, so this would need to be updated one way or another
=> remove hardcoded traceur version in utils.js

lib/builder.js
Yesterday I noticed that the config file reading part must have beend changed in recent versions, because after updating to the latest release, neither my "old" (created early november or so) config files nor those auto-generated by JSPM (__even in latest 0.17beta__) seem to be apply. This stems from arbitrarily different naming convention used for the global SystemJS/Builder instances.
JSPM is still using `SystemJS` but since a recent commit (f436a92a5e5ebba6326cc64b07026086adb01ab2) configuration files are evaluated in an isolated sandbox context where the builder isntance is only exposed as global `System`. In order to stay compatible with (older) configuration files generated by JSPM I added an alias named `SystemJS`.
=> Eval config files and expose Builder instance as both `SystemJS` and `System`

lib/builder.js, test/test-build-cache.js
Fixes #480 enabling fetch overrides for `builder.buildStatic`.
=> Fixes #480 fetch override for `builder.buildStatic`

lib/compile.js
This PR only will check UMD global compile options if globalName or globalDeps are defined as Builder options.
=> Fix for SystemJS Builder Issue #478

lib/utils.js
Provides the ability to alias modules + any additional specified path.
=> Fix for SystemJS Builder Issue #470 adding canonical path resolution.

compilers/esm.js
the `source` variable was the one that used to be sent through the transpiler, but it seems a later update went back to using load.source...
(hey, don't linters have 'unused variable' detection?)
=> esm plugins are now correctly transpiled in the legacy path (fixes systemjs/plugin-text#28)

templates/sfx-core-register.js, templates/sfx-core.js
See #559, systemjs/systemjs#1192, and systemjs/systemjs#1193. I literally copied and pasted the code from the systemjs pull request into the two templates here in the builder. I verified locally that my project (that was failing to bootstrap in the browser because of the problem) is now successfully bootstrapping.
Let me know if you'd prefer me to take the minified/built files out of this pull request. Also, I'm not sure what the `.uin.js` files are but I didn't see a way to rebuild those files.
=> Fixing #559 - runtime error when commonjs module.exports is window.location

README.md, lib/builder.js, lib/output.js
=> Fix: Output minification step breaks SourceMap chain with inlined `sourceContents` #561

compilers/amd.js
I had an issue because the builder produced the following code:
```js
(function() {
var define = $__System.amdDefine;
(function(global, factory) {
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) : typeof define === 'function' && define.amd ? define("9d", ["exports"], factory) , define("js-data", ["9d"], function(m) {
return m;
}) : (factory((global.JSData = global.JSData || {})));
}(this, function(exports) {
```
But it is not valid Javascript, the **comma** between the two `define` couldn't be correctly parsed.
I think it comes from `compilers/amd.js` with the "support for single named modules as doubling as anonymous modules". It produces two `define` separated with a comma, but when this code comes in a ternaire condition, it brokes the file.
So I propose …
=> Single named modules used as anonymous modules in ternaire conditions

templates/sfx-core-register.js, templates/sfx-core.js
This fixes jspm/jspm-cli#1793.
=> Only copying default property of commonjs modules once onto esModule. Fixes jspm#1793

lib/builder.js, lib/trace.js, test/sourcemaps.js
* Currently if the trace option `sourceMaps` is set to false, the sourceMaps will be still loaded.
This isn't valid. Once the option is set to false, it should just ignore the sourceMaps.
> References https://github.com/angular/material2/issues/541
FYI: I'm not sure, this is the correct way to transmit the trace options.
Fixes #610.
=> fix(): loader should not fetch sourcemaps if disabled.

lib/compile.js
Fixed #615 - Compile#getEncoding() should consider npm-scope package
=> Fixed  #615 - Compile#getEncoding() should consider npm-scope package

lib/builder.js
In some plugins the builder has to be accessible, for instance the WebWorker plugin.
=> Make builder accessible in plugins

lib/builder.js, test/test-build-cache.js
This is a repro for issue (1)  mentioned [here](https://github.com/frankwallis/plugin-typescript/issues/133#issuecomment-231892589) where ```load.metadata.timestamp``` is not being set and so caching is not working.
The calllback method which sets ```load.metadata.timestamp``` is never called in ```builder.loader.fetch``` because of an error [here](https://github.com/systemjs/builder/blob/master/lib/builder.js#L179)
=> demonstrate issue with load.metadata.timestamp not being set

lib/trace.js
Fixes #701 
The current exit condition is sub-optimal. As the tree of load dependencies is traversed asynchronously, it is possible that the same module's dependencies could be recursed many times. In our case, this was triggering a massive number of promises and crashing node itself.
=> prevent unnecessary recursion during trace

compilers/esm.js
This fixes #678.
In `compilers/esm.js` [L121](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L121), a workaround had been introduced for Babel not respecting the `sourceFileName` option:
```
// for some reason Babel isn't respecting sourceFileName...
if (output.map && !load.metadata.sourceMap)
output.map.sources[0] = load.path;
```
However, I believe that this option is not meant to be used along with `inputSourceMap`, as in the later case the original source file names are already embedded in the provided sourcemap, whereas `sourceFileName` is designed to provide the original file name when Babel is the entry point of the build pipeline (and the code is provided as a string and not a path).
The corresponding `sourceMapContent` test seems broken at the moment, hence no …
=> Fix Rollup + sourceMapContents: Mismatched sourcesContent

lib/rollup.js
Pass `dest` option to rollup bundle to make it convert absolute paths to relative
workaround for rollup/rollup#1015
=> workaround for #705

templates/sfx-core.js
See https://github.com/systemjs/builder/issues/734. In that issue, there are two related problems described: (1) webpack warnings, and (2) runtime error. This pull request will reduce the number of webpack warnings from two to one, and it will eliminate the runtime error. Afaik, getting rid of that last webpack warning would only be possible if we do not store System._nodeRequire, which does not seem like a likely option.
Let me know if there's something better to do here to fix the problem; I'm only about 50%-75% sure that this is a good way to resolve the issue.
Also note that this would fix https://github.com/CanopyTax/single-spa/issues/79
=> Fixing #734. Not using 'require' if process.browser is set to true

compilers/compiler.js, test/sourcemaps.js
Fixes `{ sourceMaps: 'inline' }` case. Babel was unnecessarily adding inline source maps to the output - instead it should add them to the metadata.
=> fixed inline source maps

compilers/esm.js, lib/rollup.js
Resolves issue where only source maps of `jspm_packages` were being included when building `{ sourceMaps: 'inline' }` option.
=> Fix { sourceMaps: 'inline' } option; fixes #754

docs/api.md
Added a warning that module names exist in URL space, and the bundle, buildStatic and trace argument is a module name so should be `/` separated. In reference to #814.
=> Added warning that module names exist in URL space

lib/builder.js
`uglify` option in `build` now accepts `uglify.output` consistent with the Uglify2 API.
This change does NOT change existing behaviour as the inconsistent `uglify.beautify` is still valid. Internally `uglify.output` is copied into `uglify.beautify`, when the latter is not specified. If `uglify.beautify` is specified, then `uglify.output` is ignored.
=> Add uglify.output Option in Build

lib/sourcemaps.js
If source maps already exist for the files being bundled, and if those source maps have their "sourceRoot" set to anything other than an empty string (such as "/" or "../"), then the builder fails to include the original source content in the source map for the bundle.
This happens because line 48 in sourcemaps.js fails to take into account that the source path may already be absolute, or if is relative, that it needs to be normalized.
This lack of normalization becomes a problem in line 85, where the source map itself has been normalized, while the keys for which the source content were stored are still the non-normalized paths - and therefore, the original content is not found. When it then tries to load the content from the original source file, it fails again if the original source …
=> Fix missing path normalization, causing empty sourcesContent in source maps.

lib/sourcemaps.js
This should resolve https://github.com/jspm/jspm-cli/issues/2361
=> Fix incorrect source path normalization, when the path is either rooted in a drive letter or a file url.

lib/sourcemaps.js
The utility function `fromFileURL` seem to have an inconsistent behavior, where it removes the leading `/` from the path when running on Windows, but not when running on a non-Windows system.
This inconsistency caused the issue reported in https://github.com/jspm/jspm-cli/issues/2361#issuecomment-350192381, where the source paths were only made relative to the `outPath` when building on a Windows system, thus resulting in full file system paths in source maps built on non-Windows systems.
This pull request fixes this bug.
Note that this fix is specifically to restore the correct behavior for source paths - it makes no attempt to fix the inconsistent behavior in the `fromFileURL` function, as the consequences of doing so are unclear.
=> Fix incorrect source path normalization, when the path is a file URL on a non-Windows system
