systemjs/builder

.gitignore
compilers/amd.js
compilers/cjs.js
compilers/es6.js
compilers/global.js
compilers/register.js

Opts to opt(ion)s, and dust to dust

Option forwarding

---

README.md

Useful for those just starting out with node :)

Added in path definition under Basic Use

---

index.js

This implements https://github.com/systemjs/builder/issues/19 allowing plugins to provide the following additional hook for builds:
```javascript
export function bundle(loads, opts) {
return {
source: "console.log('custom plugin code, directly included in bundle file');",
sourceMap: ... optional source map ...
};
}
```

Support plugin "bundle" reduction hook

---

index.js

@guybedford behaviour-preserving refactor to remove confusion about which compilers require sfx wrapping, and to make the automatic runtime injection easier

Remove handcoded compiler lookups and enumeration.

---

lib/builder.js
lib/sourcemaps.js
test/unit-tests.js

Ensure `sources` paths relative to source map file

---

index.js

Arithmetic composition comes into builder

---

lib/builder.js

This is just #142 with a bugfix

Enable opts as second arg in build, buildTree & buildSFX

---

compilers/esm.js

pass load.name as module name for TypeScript

---

lib/builder.js
lib/compile.js
templates/sfx-amd.js
templates/sfx-cjs.js
templates/sfx-core.js
templates/sfx-es6.js
templates/sfx-global.js

This is just a very first sketch, I haven't tested or anything. Just a placeholder for the final work.

SFX module format

---

test/test-build.js

Promises :heart: :heart_eyes_cat: :dancers:

cleaner tests, use promises rather than 'done' argument

---

lib/builder.js

Small bug fix :baby_chick: :baby_chick: :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick: :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick:  :baby_chick: :baby_chick: …

allow cache use when outFile argument not supplied

---

compilers/esm.js

this PR requires https://github.com/Microsoft/TypeScript/pull/4319 to be accepted/checked-in first.

make TypeScript transpile accept dependency map and return source maps

---

lib/output.js

Re-throw uglify parse error

---

lib/builder.js

add unhandled promise rejection handler

---

lib/arithmetic.js
lib/builder.js
lib/compile.js
lib/trace.js
lib/utils.js
package.json
test/canonicals.js
test/conditional-builds.js
test/fixtures/conditional-tree.config.js
test/fixtures/conditional-tree/conditions.js
test/fixtures/conditional-tree/interpolated-1.js
test/fixtures/conditional-tree/interpolated-2.js
test/fixtures/conditional-tree/pkg/env-condition-browser.js
test/fixtures/conditional-tree/pkg/env-condition.js

This is tracking ongoing work on conditional build support.

Conditional builds - wip

---

test/test-build-cache.js

I needed these tests to convince myself that
this API works the way I believed it to.
This is just the unit tests commit part of https://github.com/systemjs/builder/pull/374, since we're not ready to add documentation to the feature yet.

Add more tests for cache invalidation.

---

lib/builder.js
test/test-load-config.js

as discussed in   
https://github.com/systemjs/builder/pull/394#discussion_r44321335

executeConfigFile: use require('vm').executeInNewContext

---

README.md

Clarify lowResSourceMaps option

---

lib/rollup.js

inlinedLoad has depMap property. inlinedModule is just a string name.

Fix bad object reference

---

lib/builder.js

Fixes https://github.com/systemjs/builder/issues/655

Fix "this" assignment

---

package.json

There are a lot of fixes since the last version: https://github.com/rollup/rollup/blob/master/CHANGELOG.md
I personally ran into this issue and would like to see it fixed: https://github.com/rollup/rollup/issues/668

bumped rollup
